### ISSUE TITLE
Compile programs in release mode

### ISSUE THREAD

**Issue by l3kn** [niklas-heer/speed-comparison#2]
I think the results are a bit misleading
because all programs are compiled without optimizations turned on
(e.g. `-O3` for C and C++, `-C opt-level=3` for rust and `--release` for crystal).

Is that intentional?

From a quick test with the three languages above,
the times for the three languages above are much faster
and closer together.

**Comment by niklas-heer** [comment]
Hey, @l3kn thank you for your question.

No this is not intentional. Though I must say this was only a hobby project for me.
I don't think my results should be taken too seriously. For me, it was to learn about how such a project could look like and experiment with more niche programming languages.

I currently don't intend to extend the project but I welcome every contribution. 😃

**Comment by HybridDog** [comment]
Out of curiosity I have tested the leibniz.lua with 100,000,000 rounds with lua5.3 and luajit.
lua took 8.215 s and luajit did it in only 0.21 s, i.e. it is about 39 times faster.
In the Readme luajit would have approximately a score of 72 / 39 = 1.85, when not considering the overhead.

**Comment by niklas-heer** [comment]
@HybridDog thank you for sharing your findings. If you'd like to send a Pull request with your numbers/modifications I make sure to merge it. :)

**Comment by niklas-heer** [comment]
There are now new results with some optimizations in some languages.

![plot](https://raw.github.com/niklas-heer/speed-comparison/master/.github/2022-10-02_22:18.png "Speed comparison of programming languages")

I'm closing this issue for now.
If you have any more questions, just let me know.
