### ISSUE TITLE
Run make. doesn't work. Docker is installed.

### ISSUE THREAD

**Issue by igoryonya** [niklas-heer/speed-comparison#6]
$ make
docker build -t="niklas-heer/speed-comparison" .
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.39/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=wm4ti04ymz9j9bpkposspevii&shmsize=0&t=niklas-heer%2Fspeed-comparison&target=&ulimits=null&version=1: dial unix /var/run/docker.sock: connect: permission denied
Makefile:4: ошибка выполнения рецепта для цели «build»
make: *** [build] Ошибка 1

$ sudo make
[sudo] пароль для igor:
Попробуйте ещё раз.
[sudo] пароль для igor:
docker build -t="niklas-heer/speed-comparison" .
Sending build context to Docker daemon  1.666MB
Step 1/26 : FROM niklasheer/arch-python:latest
Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.0.1:53: server misbehaving
Makefile:4: ошибка выполнения рецепта для цели «build»
make: *** [build] Ошибка 1

**Comment by niklas-heer** [comment]
Hi @igoryonya thank you for your question. It seems that your docker setup isn't working. My guess would be, that your user is not part of the Docker group. (because of the `Got permission denied while trying to connect to the Docker daemon socket`)
See the [Post-installation steps for Linux](https://docs.docker.com/install/linux/linux-postinstall/)

The second part is strange maybe that can help: https://stackoverflow.com/questions/46036152/lookup-registry-1-docker-io-no-such-host/46037636
